### ISSUE TITLE
1.4.0 to 1.5.0 upgrade problem

### ISSUE THREAD

**Issue by YouCanNotBeSerious** [lucavb/homebridge-esphome-ts#113]
**I upgraded, and had an issue that from the logs seemed to be about HAP/bonjour not being installed or working properly.....so i reverted to 1.4.0**

Before i retry, post logs, etc is this something known ?  If not, what debug would you like posted?

BTW i am genuinely asking the above, with no intended "tone"!  This esphome plugin was a lifesaver for me, i tried let's say another one and it was harder to setup, did not work as well, and used REST not the native API. So thanks for providing this plugin :-)

**Comment by Veldkornet** [comment]
I also received that error:

```
[7/2/2021, 9:20:13 AM] ====================
[7/2/2021, 9:20:13 AM] ERROR LOADING PLUGIN homebridge-esphome-ts:
[7/2/2021, 9:20:13 AM] Error: Cannot find module 'bonjour-hap'
Require stack:
- /homebridge/node_modules/homebridge-esphome-ts/dist/discovery.js
- /homebridge/node_modules/homebridge-esphome-ts/dist/platform.js
- /homebridge/node_modules/homebridge-esphome-ts/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-esphome-ts/dist/discovery.js:7:39)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
[7/2/2021, 9:20:13 AM] ====================
```

**Comment by OE5DRO** [comment]
same here

**Comment by lucavb** [comment]
1.5.1 should fix it :)

**Comment by OE5DRO** [comment]
tnx for fast fix, its workin' again

**Comment by YouCanNotBeSerious** [comment]
Yes, confirming the update from 1.4.0 -> 1.5.1 worked fine for me. Thanks again for this plugin!
