### ISSUE TITLE
Error trying to start

### ISSUE THREAD

**Issue by MDo3** [lucavb/homebridge-esphome-ts#224]
Does this plugin require a specific node version?

I am using version: v8.9.4

Homebridge throws an error when trying to start:

(node:19241) Warning: N-API is an experimental feature and could change at any time.
[2021-12-26 08:02:40] Homebridge is running on port 51826.
[2021-12-26 08:02:40] [esphome] HAP Device discovered esp32
/usr/lib/node_modules/homebridge-esphome-ts/node_modules/rxjs/dist/cjs/internal/util/reportUnhandledError.js:13
            throw err;
            ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:701:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/usr/lib/node_modules/homebridge-esphome-ts/node_modules/esphome-ts/dist/api/socket.js:52:29)
    at Observable._trySubscribe (/usr/lib/node_modules/homebridge-esphome-ts/node_modules/rxjs/dist/cjs/internal/Observable.js:71:25)
    at Observable.subscribe (/usr/lib/node_modules/homebridge-esphome-ts/node_modules/rxjs/dist/cjs/internal/Observable.js:36:30)
    at source.subscribe.OperatorSubscriber_1.OperatorSubscriber.isComplete (/usr/lib/node_modules/homebridge-esphome-ts/node_modules/rxjs/dist/cjs/internal/operators/switchMap.js:17:58)
    at OperatorSubscriber._this._next (/usr/lib/node_modules/homebridge-esphome-ts/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
    at OperatorSubscriber.Subscriber.next (/usr/lib/node_modules/homebridge-esphome-ts/node_modules/rxjs/dist/cjs/internal/Subscriber.js:71:18)
    at /usr/lib/node_modules/homebridge-esphome-ts/node_modules/rxjs/dist/cjs/internal/operators/take.js:15:32
    at OperatorSubscriber._this._next (/usr/lib/node_modules/homebridge-esphome-ts/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
    at OperatorSubscriber.Subscriber.next (/usr/lib/node_modules/homebridge-esphome-ts/node_modules/rxjs/dist/cjs/internal/Subscriber.js:71:18)
osmc@osmc:~$

**Comment by lucavb** [comment]
I would guess so. The tests for it are running on at least node 10. Any reason why you are on such an old version? I think even recent versions of homebridge doesn't support it anymore.
